import { z } from 'zod';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { textResult, normalizeHex, hexToHsl, hslToHex } from '../util.js';

/** Build a 16-slot Fluent BrandVariants ramp (10..160) from one brand hex, anchored at slot 80.
 *  Interpolates in HSL (lightness), tapering saturation toward the light end for a smoother ramp. */
function buildBrandRamp(brand: string): Record<string, string> {
  const [h, s, l0] = hexToHsl(brand);
  const slots: Record<string, string> = {};
  const dark: Array<[string, number]> = [
    ['10', 0.16], ['20', 0.3], ['30', 0.44], ['40', 0.58], ['50', 0.72], ['60', 0.84], ['70', 0.93],
  ];
  for (const [k, f] of dark) {
    const L = 0.07 + (l0 - 0.07) * f;
    slots[k] = hslToHex(h, s, Math.min(1, Math.max(0, L)));
  }
  slots['80'] = brand;
  const light: Array<[string, number]> = [
    ['90', 0.22], ['100', 0.42], ['110', 0.55], ['120', 0.66], ['130', 0.77], ['140', 0.86], ['150', 0.93], ['160', 0.985],
  ];
  for (const [k, f] of light) {
    const L = l0 + (0.975 - l0) * f;
    const S = s * (1 - 0.45 * f);
    slots[k] = hslToHex(h, Math.min(1, Math.max(0, S)), Math.min(1, Math.max(0, L)));
  }
  return slots;
}

export function registerTheme(server: McpServer): void {
  server.registerTool(
    'fluent_generate_theme',
    {
      title: 'Generate a Fluent 2 brand theme',
      description:
        'Turn a single brand hex into a Fluent 2 BrandVariants ramp (16 slots) plus ready-to-use TypeScript that builds light + dark themes with createLightTheme/createDarkTheme, and the brand CSS variables. Neutral/semantic tokens come from the official functions (webLightTheme/webDarkTheme).',
      inputSchema: {
        brandColor: z
          .string()
          .regex(/^#?[0-9a-fA-F]{6}$/)
          .describe('Brand hex, e.g. #0F6CBD.'),
        name: z
          .string()
          .regex(/^[A-Za-z_$][A-Za-z0-9_$]*$/)
          .default('brand')
          .describe('A valid JS identifier used for the exported theme variables.'),
      },
    },
    async ({ brandColor, name }) => {
      const brand = normalizeHex(brandColor);
      const ramp = buildBrandRamp(brand);
      const bvLines = Object.entries(ramp)
        .map(([k, v]) => `  ${k}: '${v}',`)
        .join('\n');
      const cssLines = Object.entries(ramp)
        .map(([k, v]) => `  --colorBrand${k}: ${v};`)
        .join('\n');
      const ts =
        `import {\n  BrandVariants,\n  Theme,\n  createLightTheme,\n  createDarkTheme,\n} from '@fluentui/react-components';\n\n` +
        `export const ${name}: BrandVariants = {\n${bvLines}\n};\n\n` +
        `export const ${name}LightTheme: Theme = createLightTheme(${name});\n` +
        `export const ${name}DarkTheme: Theme = createDarkTheme(${name});\n\n` +
        `// Usage:\n// <FluentProvider theme={${name}LightTheme}> ...your app... </FluentProvider>`;
      return textResult(
        `Fluent 2 brand theme for ${brand}\n\n` +
          `// theme.ts\n${ts}\n\n` +
          `/* Brand ramp as CSS custom properties */\n:root {\n${cssLines}\n}\n\n` +
          `Notes:\n` +
          `- createLightTheme/createDarkTheme (from @fluentui/react-components) produce the full official Fluent 2 theme (neutral + semantic tokens) from this brand ramp.\n` +
          `- The 16-slot ramp is generated by HSL lightness interpolation anchored at slot 80 = your brand (saturation tapers toward the light end for a smoother ramp). For a perceptually exact ramp the Fluent 2 Theme Designer can also be used; the createLightTheme/createDarkTheme output remains official either way.`
      );
    }
  );
}
