import { z } from 'zod';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { loadJson, textResult } from '../util.js';

function walkTokens(
  obj: any,
  path: string[],
  out: Array<{ path: string; value: any }>
): void {
  for (const [k, v] of Object.entries(obj)) {
    const p = [...path, k];
    if (v && typeof v === 'object' && !Array.isArray(v)) walkTokens(v, p, out);
    else out.push({ path: p.join('.'), value: v });
  }
}

/**
 * The shipped Griffel/CSS names for tokens the dataset stores under a nested
 * path. `typography.fontFamilies.base` is real data but `tokens.fontFamilies.base`
 * does not exist in Griffel — the shipped name is `tokens.fontFamilyBase` /
 * `--fontFamilyBase`. Without this alias layer fluent_get_token cannot resolve
 * the three font-family tokens at all, and fluent_list_tokens teaches models to
 * write a Griffel path that is undefined at runtime.
 *
 * Fixing this in the tool rather than the data is deliberate: mcp/data is shared.
 */
const TOKEN_ALIASES: Record<string, string> = {
  fontfamilybase: 'typography.fontFamilies.base',
  fontfamilymonospace: 'typography.fontFamilies.monospace',
  fontfamilynumeric: 'typography.fontFamilies.numeric',
};

/** Reverse map: dataset path -> the real shipped token name. */
const SHIPPED_NAME_BY_PATH: Record<string, string> = {
  'typography.fontFamilies.base': 'fontFamilyBase',
  'typography.fontFamilies.monospace': 'fontFamilyMonospace',
  'typography.fontFamilies.numeric': 'fontFamilyNumeric',
};

/** How many substring matches to return before switching to a count + advice. */
const MAX_FUZZY_MATCHES = 25;

/** How many design-name bridge rows to attach to one lookup. */
const MAX_BRIDGE_HITS = 6;

/**
 * The design-name -> code-token bridge (fluent-tokens.json -> designNameBridge,
 * generated by scripts/build-design-token-bridge.mjs).
 *
 * It exists because the two vocabularies are OFFSET, not merely different: the
 * Fluent 2 site's "Large" corner radius is 8px, and `borderRadiusLarge` is 6px.
 * A model that reads the design guidance and writes the design name as a token
 * name compiles cleanly and renders the wrong value. Resolving the design name
 * here is what turns that silent failure into an answer.
 */
interface BridgeEntry {
  id: string;
  kind: string;
  designName: string;
  designLabel?: string;
  designValue?: unknown;
  codeToken: string | null;
  codeTokens?: unknown;
  codeValue?: unknown;
  codeSymbol?: string;
  codePackage?: string;
  codeStyle?: string;
  valueMatch?: string;
  griffel?: string;
  cssVar?: string;
  usage?: string;
  reason?: string;
  note?: string;
  caution?: string;
  warning?: string;
  collisionSeverity?: string;
  expectedCodeName?: string;
  expectedCodeNameActualValue?: string;
  mismatches?: unknown;
  lookupKeys?: string[];
  docUrl?: string;
}

/** Lowercase, strip every separator: "Large corner radius" -> "largecornerradius". */
const slug = (s: string) => String(s).toLowerCase().replace(/[^a-z0-9]+/g, '');

let bridgeIndexCache: Map<string, BridgeEntry[]> | null = null;

/** lookupKey -> entries. Built once; the dataset does not change at runtime. */
function bridgeIndex(t: any): Map<string, BridgeEntry[]> {
  if (bridgeIndexCache) return bridgeIndexCache;
  const map = new Map<string, BridgeEntry[]>();
  for (const e of (t?.designNameBridge?.entries ?? []) as BridgeEntry[]) {
    for (const key of e.lookupKeys ?? []) {
      const k = slug(key);
      if (!k) continue;
      const list = map.get(k) ?? [];
      if (!list.includes(e)) list.push(e);
      map.set(k, list);
    }
  }
  bridgeIndexCache = map;
  return map;
}

/** The rows a caller actually wants to see — not the whole generated record. */
function compactBridge(e: BridgeEntry): Record<string, unknown> {
  const out: Record<string, unknown> = {
    designName: e.designName,
    designLabel: e.designLabel,
    designValue: e.designValue,
    kind: e.kind,
    codeToken: e.codeToken,
    codeValue: e.codeValue,
    valueMatch: e.valueMatch,
  };
  for (const k of [
    'codeTokens',
    'codeStyle',
    'codeSymbol',
    'codePackage',
    'griffel',
    'cssVar',
    'usage',
    'collisionSeverity',
    'expectedCodeName',
    'expectedCodeNameActualValue',
    'mismatches',
    'warning',
    'reason',
    'note',
    'caution',
    'docUrl',
  ] as const) {
    if ((e as any)[k] !== undefined) out[k] = (e as any)[k];
  }
  return out;
}

/** Design-side names (and their px forms) that resolve to this query. */
function resolveDesignName(t: any, q: string): BridgeEntry[] {
  const hits = bridgeIndex(t).get(slug(q));
  return hits ? hits.slice(0, MAX_BRIDGE_HITS) : [];
}

/**
 * A code token that is itself one half of a name collision. Attached whenever a
 * lookup lands on `borderRadiusLarge` from either direction, so the offset is
 * stated at the exact moment someone is about to use the wrong step.
 */
function collisionsForResults(t: any, resultKeys: string[]): Record<string, unknown> | undefined {
  const map = t?.designNameBridge?.collisionsByCodeToken;
  if (!map) return undefined;
  const out: Record<string, unknown> = {};
  for (const key of resultKeys) {
    const leaf = key.replace(/\s*\(.*\)$/, '').split('.').pop();
    if (leaf && map[leaf] && !out[leaf]) out[leaf] = map[leaf];
  }
  return Object.keys(out).length ? out : undefined;
}

/** Compact per-category rows for fluent_list_tokens. */
function designNameRows(t: any, category: string): Array<Record<string, unknown>> | undefined {
  const kinds: Record<string, string[]> = {
    borderRadius: ['cornerRadius'],
    strokeWidth: ['strokeWidth'],
    spacing: ['spacing'],
    typography: ['typeRamp'],
    color: ['color'],
  };
  const want = kinds[category];
  if (!want) return undefined;
  const rows = ((t?.designNameBridge?.entries ?? []) as BridgeEntry[])
    .filter((e) => want.includes(e.kind))
    .map((e) => {
      const row: Record<string, unknown> = {
        designName: e.designName,
        designValue: e.designValue,
        codeToken: e.codeToken,
        codeValue: e.codeValue,
        valueMatch: e.valueMatch,
      };
      if (e.warning) row.nameCollisionWarning = e.warning;
      if (e.reason && !e.codeToken) row.reason = e.reason;
      return row;
    });
  return rows.length ? rows : undefined;
}

const BRIDGE_NOTE =
  'designNames maps the names Microsoft publishes on fluent2.microsoft.design to the code tokens that actually ' +
  'produce those values, matched BY VALUE. The two scales are offset in places — the site\'s "Large" corner radius ' +
  'is 8px, which is borderRadiusXLarge; borderRadiusLarge is 6px. Never turn a design name into a token name yourself.';

/**
 * Categories whose values are theme-invariant in this dataset. Reported
 * explicitly so a caller never assumes `theme` was honoured when it was not.
 */
const THEME_INVARIANT = new Set(['typography', 'spacing', 'borderRadius', 'strokeWidth', 'motion', 'shadow']);

/**
 * Fluent 2 ships distinct dark-theme shadow values (and shadow*Brand variants
 * for use over brand fills). This dataset carries a single set, so `theme` is a
 * no-op for shadows and that has to be stated rather than implied.
 */
const SHADOW_CAVEAT =
  'theme does NOT affect this category here: mcp/data/fluent-tokens.json carries a single shadow set ' +
  '(plus the shadow*Brand variants). Fluent 2 does define separate dark-theme shadow values, so for a dark ' +
  'surface read tokens.shadowN from webDarkTheme at runtime rather than pasting these literals.';

function themeNote(category: string): string | undefined {
  if (category === 'shadow') return SHADOW_CAVEAT;
  if (THEME_INVARIANT.has(category)) return 'theme does not affect this category: these values are theme-invariant.';
  return undefined;
}

export function registerTokens(server: McpServer): void {
  server.registerTool(
    'fluent_list_tokens',
    {
      title: 'List Fluent 2 design tokens',
      description:
        'List Fluent 2 design tokens by category (color, typography, spacing, borderRadius, strokeWidth, shadow, motion). For color, choose the theme (light/dark/highContrast) — the color response also carries aliasGlobalTokens, the published alias-token to global-token-slot map (colorBrandBackground -> brand[80] light / brand[70] dark). Every other category is theme-invariant in this dataset and the response says so explicitly. Values are concrete resolved values; each token X is exposed as the CSS variable --X and as tokens.X in Griffel makeStyles. Categories that have one also return designNames: the design-site names from fluent2.microsoft.design mapped BY VALUE to these code tokens, because the two scales are offset — the site\'s "Large" corner radius is 8px = borderRadiusXLarge, while borderRadiusLarge is 6px.',
      inputSchema: {
        category: z
          .enum(['color', 'typography', 'spacing', 'borderRadius', 'strokeWidth', 'shadow', 'motion', 'all'])
          .default('all'),
        theme: z
          .enum(['light', 'dark', 'highContrast'])
          .default('light')
          .describe('Theme for color tokens. Ignored (and reported as ignored) for every other category.'),
      },
    },
    async ({ category, theme }) => {
      const t = loadJson<any>('fluent-tokens.json');
      if (!t) return textResult('Token data not found at mcp/data/fluent-tokens.json.');
      const themeKey =
        theme === 'dark' ? 'semanticDark' : theme === 'highContrast' ? 'semanticHighContrast' : 'semanticLight';
      if (category === 'color') {
        const meta = t.color?.aliasReferenceMeta;
        return textResult(
          JSON.stringify(
            {
              theme,
              brandRamp: t.color.brandRamp,
              [themeKey]: t.color[themeKey],
              aliasGlobalTokens: globalSlotMap(t),
              aliasGlobalTokensNote: meta
                ? 'aliasGlobalTokens records which global token slot (family[slot]) each alias resolves to in the light and ' +
                  'dark web themes — provenance, not a substitute for the concrete values above. Source: ' +
                  meta.docUrl
                : undefined,
              designNames: designNameRows(t, 'color'),
              designNamesNote: BRIDGE_NOTE,
            },
            null,
            2
          )
        );
      }
      if (category === 'all') {
        return textResult(
          JSON.stringify(
            {
              theme,
              themeNote:
                'theme applies to colorSemantic only. Every other category below is theme-invariant in this dataset. ' +
                SHADOW_CAVEAT,
              designNameBridgeNote:
                'Design-site names (Large corner radius, size120, Body 1) are NOT these token names and are offset in ' +
                'places. Ask for one category to get its designNames map, or call fluent_get_token { name: ' +
                '"Large corner radius" } / { name: "size120" }.',
              colorBrandRamp: t.color.brandRamp,
              colorSemantic: t.color[themeKey],
              typography: withShippedNames(t.typography),
              spacing: t.spacing,
              borderRadius: t.borderRadius,
              strokeWidth: t.strokeWidth,
              shadow: t.shadow,
              motion: t.motion,
            },
            null,
            2
          )
        );
      }
      const note = themeNote(category);
      const value = category === 'typography' ? withShippedNames(t[category]) : t[category];
      const designNames = designNameRows(t, category);
      return textResult(
        JSON.stringify(
          {
            category,
            ...(note ? { theme, note } : {}),
            [category]: value,
            ...(designNames ? { designNames, designNamesNote: BRIDGE_NOTE } : {}),
          },
          null,
          2
        )
      );
    }
  );

  server.registerTool(
    'fluent_get_token',
    {
      title: 'Get a Fluent 2 design token value',
      description:
        'Look up a Fluent 2 design token by name (e.g. colorBrandBackground, spacingHorizontalM, borderRadiusMedium, fontSizeBase300, fontFamilyBase, shadow8, durationNormal). Returns concrete value(s) across light/dark/high-contrast where applicable plus the CSS variable name. ALSO resolves DESIGN-SITE names — the vocabulary fluent2.microsoft.design and fluent_design_guidance use — to the code token that actually produces that value: "Large corner radius" -> borderRadiusXLarge (8px), "size120" -> spacingHorizontalM/spacingVerticalM (12px), "Body 1" -> body1 / fontSizeBase300, "dark theme" -> webDarkTheme. The two scales are OFFSET, so this is not cosmetic: borderRadiusLarge is 6px, not the 8px the site calls Large. Any lookup that lands on one side of that offset comes back with $nameCollisionWarning. An empty or whitespace-only name is rejected rather than treated as "match everything"; a broad fragment returns a capped list plus the total match count.',
      inputSchema: {
        name: z
          .string()
          .min(1, 'name must not be empty — pass a token name or fragment, e.g. "colorBrandBackground".')
          .describe(
            'Token name or fragment (colorBrandBackground), or a Fluent 2 design-site name ("Large corner radius", "size120", "Body 1", "dark theme").'
          ),
        maxMatches: z
          .number()
          .int()
          .min(1)
          .max(500)
          .default(MAX_FUZZY_MATCHES)
          .describe('Cap on the number of substring (fragment) matches returned. Exact matches are never capped.'),
      },
    },
    async ({ name, maxMatches }) => {
      const t = loadJson<any>('fluent-tokens.json');
      if (!t) return textResult('Token data not found.');

      // An empty/whitespace query used to fall through to the substring branch,
      // where `includes('')` matches every token and dumped the entire dataset
      // as if it were an answer.
      if (!name || !name.trim()) {
        return textResult(
          'Empty token name. Pass a token name or fragment, e.g. fluent_get_token { name: "colorBrandBackground" }, ' +
            'or browse a category with fluent_list_tokens { category: "color" }.'
        );
      }

      const q = name.trim().toLowerCase().replace(/^--/, '');
      const results: Record<string, any> = {};

      for (const [themeName, key] of [
        ['light', 'semanticLight'],
        ['dark', 'semanticDark'],
        ['highContrast', 'semanticHighContrast'],
      ] as const) {
        const sec = t.color?.[key] || {};
        for (const [k, v] of Object.entries(sec)) {
          if (k.toLowerCase() === q) results[`color.${themeName}.${k}`] = v;
        }
      }

      const out: Array<{ path: string; value: any }> = [];
      for (const cat of ['typography', 'spacing', 'borderRadius', 'strokeWidth', 'shadow', 'motion']) {
        if (t[cat]) walkTokens(t[cat], [cat], out);
      }
      for (const e of out) {
        const leaf = e.path.split('.').pop()!.toLowerCase();
        if (leaf === q) results[label(e.path)] = e.value;
      }

      // Exact hit on a shipped name the dataset stores under a nested path.
      const aliasPath = TOKEN_ALIASES[q];
      if (aliasPath) {
        const hit = out.find((e) => e.path === aliasPath);
        if (hit) results[label(aliasPath)] = hit.value;
      }

      const exactCount = Object.keys(results).length;
      let fuzzyTotal = 0;
      if (exactCount === 0) {
        const fuzzy: Array<[string, any]> = [];
        for (const [k, v] of Object.entries(t.color?.semanticLight || {})) {
          if (k.toLowerCase().includes(q)) fuzzy.push([`color.light.${k}`, v]);
        }
        for (const e of out) {
          const shipped = SHIPPED_NAME_BY_PATH[e.path];
          if (e.path.toLowerCase().includes(q) || (shipped && shipped.toLowerCase().includes(q))) {
            fuzzy.push([label(e.path), e.value]);
          }
        }
        fuzzyTotal = fuzzy.length;
        for (const [k, v] of fuzzy.slice(0, maxMatches)) results[k] = v;
      }

      // Design-side names resolve here, and only on an exact lookup-key hit:
      // "Large corner radius", "size120", "Body 1", "dark theme". Matching by
      // fragment instead would bury the values the caller asked for.
      const bridgeHits = resolveDesignName(t, name);

      if (Object.keys(results).length === 0 && bridgeHits.length === 0) {
        return textResult(
          `No token matching "${name}". Use fluent_list_tokens to browse categories. ` +
            'If this is a name from the Fluent 2 design site (e.g. "Large corner radius", "size120", "Body 1", ' +
            '"dark theme"), it is a design-language name, not a token name — this tool resolves those too, so check ' +
            'the exact wording.'
        );
      }

      // Colour aliases carry provenance the resolved hex cannot: which global
      // slot they point at per theme, the interaction state, and the category
      // the design system files them under. Attached only for a narrow result
      // set — on a broad fragment it would bury the values the caller asked for.
      const aliasRefs = aliasReferencesFor(t, Object.keys(results));
      if (Object.keys(aliasRefs).length) {
        results.$aliasReference = {
          note: 'Global token slot (family[slot]) each alias resolves to per theme, plus its state and published category.',
          docUrl: t.color?.aliasReferenceMeta?.docUrl,
          tokens: aliasRefs,
        };
      }

      // The offset is the whole point of the bridge: state it on the way in
      // (someone asked for borderRadiusLarge) as well as on the way out
      // (someone asked for "Large corner radius").
      const collisions = collisionsForResults(t, Object.keys(results));
      if (collisions) {
        results.$nameCollisionWarning = {
          note:
            'A token here shares its name with a DIFFERENT step of the Fluent 2 design-site scale. Read this before ' +
            'trusting a token name that came from design guidance.',
          tokens: collisions,
        };
      }

      if (bridgeHits.length) {
        results.$designNameBridge = {
          note:
            `"${name}" is a Fluent 2 design-site name. Resolved to the code token that produces the same value, ` +
            'matched by value rather than by name.',
          matched: bridgeHits.length,
          resolved: bridgeHits.map(compactBridge),
        };
      }

      const header =
        exactCount > 0
          ? `Exact match(es) for "${name}"`
          : fuzzyTotal > maxMatches
            ? `"${name}" is a fragment, not a token name: ${fuzzyTotal} matches, showing ${maxMatches}. Narrow the query or use fluent_list_tokens to browse.`
            : fuzzyTotal === 0 && bridgeHits.length > 0
              ? `"${name}" is a design-site name, not a token name — resolved through the design-name bridge`
              : `"${name}" matched ${fuzzyTotal} token(s) by fragment`;

      return textResult(
        `${header} — each token X maps to CSS variable --X and tokens.X in Griffel:\n\n` +
          JSON.stringify(results, null, 2)
      );
    }
  );
}

/**
 * The published alias -> global-token-slot map, flattened to one readable line
 * per alias. Kept compact deliberately: the concrete per-theme values are
 * already in the same response, so repeating the full record for 348 aliases
 * would triple the payload to say the same thing.
 */
function globalSlotMap(t: any): Record<string, string> | undefined {
  const ref = t?.color?.aliasReference;
  if (!ref) return undefined;
  const out: Record<string, string> = {};
  for (const [name, entry] of Object.entries<any>(ref)) {
    out[name] = `${entry?.globalLight ?? 'n/a'} (light) / ${entry?.globalDark ?? 'n/a'} (dark)`;
  }
  return out;
}

/** Alias-reference records for the colour tokens a lookup actually matched. */
function aliasReferencesFor(t: any, resultKeys: string[]): Record<string, any> {
  const ref = t?.color?.aliasReference;
  if (!ref) return {};
  const names = new Set<string>();
  for (const key of resultKeys) {
    const m = /^color\.(?:light|dark|highContrast)\.(.+)$/.exec(key);
    if (m && ref[m[1]]) names.add(m[1]);
  }
  if (names.size === 0 || names.size > 12) return {};
  const out: Record<string, any> = {};
  for (const n of names) out[n] = ref[n];
  return out;
}

/**
 * Label a dataset path with the real shipped token name where the two differ,
 * so a caller is never handed `typography.fontFamilies.base` alone and left to
 * guess the Griffel key.
 */
function label(path: string): string {
  const shipped = SHIPPED_NAME_BY_PATH[path];
  return shipped ? `${shipped} (${path})` : path;
}

/** Add the shipped `fontFamily*` names alongside the nested `fontFamilies` map. */
function withShippedNames(typography: any): any {
  if (!typography || typeof typography !== 'object' || !typography.fontFamilies) return typography;
  const families = typography.fontFamilies;
  const shipped: Record<string, any> = {};
  for (const [path, tokenName] of Object.entries(SHIPPED_NAME_BY_PATH)) {
    const leaf = path.split('.').pop()!;
    if (families[leaf] !== undefined) shipped[tokenName] = families[leaf];
  }
  return {
    ...typography,
    // The nested map is the dataset shape; these are the names that actually
    // exist as tokens.X in Griffel and --X in CSS. Use these in code.
    fontFamilyTokens: shipped,
    fontFamilyTokensNote:
      'Use fontFamilyBase / fontFamilyMonospace / fontFamilyNumeric in code (tokens.fontFamilyBase, --fontFamilyBase). ' +
      '"fontFamilies.base" is this dataset\'s storage path, not a Griffel key.',
  };
}
