/*
 * HelloFluent — index.ts (illustrative PCF *virtual* React control)
 *
 * Demonstrates the Fluent-2 essentials for PCF:
 *   - A ReactControl whose `updateView` RETURNS a React element (no manual ReactDOM.render,
 *     and `init` has no `div` parameter — the platform renders the returned tree).
 *   - Consuming the host app's Fluent 2 theme via `context.fluentDesignLanguage`.
 *   - Wrapping the tree in a `FluentProvider` so the component matches the app theme.
 *
 * This is a teaching sample, not a full build. Scaffold a real project with:
 *   pac pcf init -n HelloFluent -ns SampleNamespace -t field -fw react -npm
 *
 * Docs:
 *   - Style components with modern theming: https://learn.microsoft.com/power-apps/developer/component-framework/fluent-modern-theming
 *   - Theming API (context.fluentDesignLanguage): https://learn.microsoft.com/power-apps/developer/component-framework/reference/theming
 *   - ReactControl: https://learn.microsoft.com/power-apps/developer/component-framework/reference/react-control
 */

import * as React from "react";
import { FluentProvider, webLightTheme, webDarkTheme } from "@fluentui/react-components";
import { HelloFluentCard, IHelloFluentCardProps } from "./HelloFluent";
// Generated by `pac pcf init` / `npm run build`. Bound properties become inputs *and* outputs.
import { IInputs, IOutputs } from "./generated/ManifestTypes";

// Class name must match the manifest's constructor="HelloFluent".
export class HelloFluent
  implements ComponentFramework.ReactControl<IInputs, IOutputs>
{
  private notifyOutputChanged: () => void;
  private label = "";
  private clickCount = 0;

  /**
   * init — React controls don't receive a container div; they don't render the DOM directly.
   * Kick off any one-time setup here (dataset controls initialize values in updateView).
   */
  public init(
    context: ComponentFramework.Context<IInputs>,
    notifyOutputChanged: () => void
  ): void {
    this.notifyOutputChanged = notifyOutputChanged;
  }

  /**
   * updateView — called whenever a bound value or framework aspect changes.
   * Returns the React tree; the platform renders it. We wrap the component in a
   * FluentProvider using the host's Fluent 2 theme so it matches the surrounding app.
   */
  public updateView(
    context: ComponentFramework.Context<IInputs>
  ): React.ReactElement {
    this.label = context.parameters.label.raw ?? "Hello, Fluent 2!";
    this.clickCount = context.parameters.clickCount.raw ?? 0;

    // Consume the platform-provided Fluent v9 theme when modern theming is enabled.
    // NOTE: the docs use `tokenTheme` (Theming reference) but some samples use `.theme`;
    // `tokenTheme` is the reference-aligned property. Guard with optional chaining so the
    // control still renders (falling back to the web light/dark theme) when theming is off.
    const fdl = context.fluentDesignLanguage;
    const theme =
      fdl?.tokenTheme ?? (fdl?.isDarkTheme ? webDarkTheme : webLightTheme);

    const props: IHelloFluentCardProps = {
      label: this.label,
      clickCount: this.clickCount,
      onClick: () => {
        this.clickCount += 1;
        this.notifyOutputChanged(); // pushes clickCount back; triggers another updateView
      },
    };

    return React.createElement(
      FluentProvider,
      { theme },
      React.createElement(HelloFluentCard, props)
    );
  }

  /**
   * getOutputs — return values for every `usage="bound"` property in the manifest.
   */
  public getOutputs(): IOutputs {
    return {
      label: this.label,
      clickCount: this.clickCount,
    };
  }

  /**
   * destroy — cleanup. React controls unmount automatically; release other resources here.
   */
  public destroy(): void {
    // no-op for this sample
  }
}
